version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "aaccioly"

- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
    - "aaccioly"
